name: CI

on:
  push:
    tags:
      - 'v*'
    branches:
    - '**'
    - '!dependabot/**'
  pull_request: {}

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-go@v2
      with:
        go-version: '1.13'
    - name: Install pack
      run: (export GH=buildpacks/pack; export LATEST=$(curl -s https://api.github.com/repos/$GH/releases/latest | grep -o -E "https://.+?-linux.tgz" | head -1); echo "$LATEST"; curl -sSL "$LATEST" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv $(basename $GH))
    - name: Create Builder
      run: make build
    - name: Test Builder
      run: |
        git config --global --bool --add advice.detachedHead false
        make test

  publish:
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: gcloud auth
      run: |
        gcloud config set disable_prompts True
        gcloud auth activate-service-account --key-file <(echo $GCLOUD_CLIENT_SECRET | base64 --decode)
        gcloud auth configure-docker
      env:
        GCLOUD_CLIENT_SECRET: ${{ secrets.GCLOUD_CLIENT_SECRET }}
    - name: Publish Builder
      run: .github/workflows/push-buildtemplate-to-gcs.sh ${{ github.ref }}
