name: Update Build Image
"on":
    schedule:
        - cron: 0 5 * * 1-5
    workflow_dispatch: {}
jobs:
    update:
        name: Update Build Image
        runs-on:
            - ubuntu-latest
        steps:
            - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
              name: Docker login gcr.io
              uses: docker/login-action@v1
              with:
                password: ${{ secrets.RIFF_GCLOUD_SERVICE_ACCOUNT_KEY }}
                registry: gcr.io
                username: _json_key
            - uses: actions/setup-go@v2
              with:
                go-version: "1.15"
            - name: Install update-build-image-dependency
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                GO111MODULE=on go get -u -ldflags="-s -w" github.com/paketo-buildpacks/libpak/cmd/update-build-image-dependency
            - name: Install crane
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                echo "Installing crane ${CRANE_VERSION}"

                mkdir -p "${HOME}"/bin
                echo "${HOME}/bin" >> "${GITHUB_PATH}"

                curl \
                  --show-error \
                  --silent \
                  --location \
                  "https://github.com/google/go-containerregistry/releases/download/v${CRANE_VERSION}/go-containerregistry_Linux_x86_64.tar.gz" \
                | tar -C "${HOME}/bin" -xz crane
              env:
                CraneVersion: 0.1.4
            - name: Install yj
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                echo "Installing yj ${YJ_VERSION}"

                mkdir -p "${HOME}"/bin
                echo "${HOME}/bin" >> "${GITHUB_PATH}"

                curl \
                  --location \
                  --show-error \
                  --silent \
                  --output "${HOME}"/bin/yj \
                  "https://github.com/sclevine/yj/releases/download/v${YJ_VERSION}/yj-linux"

                chmod +x "${HOME}"/bin/yj
              env:
                YJ_VERSION: 5.0.0
            - uses: actions/checkout@v2
            - id: build-image
              name: Update Build Image Dependency
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                OLD_VERSION=$(yj -tj < builder.toml | jq -r ".stack.\"build-image\" | capture(\"${IMAGE}:(?<version>.+-${CLASSIFIER})\") | .version")
                NEW_VERSION=$(crane ls "${IMAGE}" | grep ".*-${CLASSIFIER}" | sort -V | tail -n 1)

                update-build-image-dependency \
                  --builder-toml builder.toml \
                  --version "${NEW_VERSION}"

                git add builder.toml
                git checkout -- .

                echo "::set-output name=old-version::${OLD_VERSION}"
                echo "::set-output name=new-version::${NEW_VERSION}"
              env:
                CLASSIFIER: base-cnb
                IMAGE: gcr.io/paketo-buildpacks/build
            - uses: peter-evans/create-pull-request@v3
              with:
                body: Bumps [`gcr.io/paketo-buildpacks/build`](https://gcr.io/paketo-buildpacks/build) from [`${{ steps.build-image.outputs.old-version }}`](https://gcr.io/paketo-buildpacks/build:${{ steps.build-image.outputs.old-version }}) to [`${{ steps.build-image.outputs.new-version }}`](https://gcr.io/paketo-buildpacks/build:${{ steps.build-image.outputs.new-version }}).
                branch: update/build-image/build
                commit-message: |-
                    Bump gcr.io/paketo-buildpacks/build from ${{ steps.build-image.outputs.old-version }} to ${{ steps.build-image.outputs.new-version }}

                    Bumps gcr.io/paketo-buildpacks/build from ${{ steps.build-image.outputs.old-version }} to ${{ steps.build-image.outputs.new-version }}.
                delete-branch: true
                labels: semver:minor, type:dependency-upgrade
                signoff: true
                title: Bump gcr.io/paketo-buildpacks/build from ${{ steps.build-image.outputs.old-version }} to ${{ steps.build-image.outputs.new-version }}
                token: ${{ secrets.RIFF_GITHUB_TOKEN }}
